collections:
  demos:
    output: true
    permalink: /:collection/:path/
#
# Site settings
title: gaogao
email: gaogao1130@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  変態じゃないよ、仮に変態だとしても変態という名の紳士だよ！
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gaogao1030.github.io" # the base hostname & protocol for your site
twitter_username: gaogao1030
github_username:  gaogao1030

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: 'rouge'

timezone: '+0800'
permalink: '/:categories/:year/:month/:day/:title'

exclude: ["Rakefile",".ruby-version","Gemfile","Gemfile.lock","readme.md","initializers","qiniu.yml","bower.json","bower_components","run","gulp_config.json","gulpfile.coffee","node_modules","package.json"]
keep_files: [".git","CNAME",".nojekyll"]

paginate: 10
jekyll-archives:
  enabled: all

gems:
  - jekyll-archives


defaults:
  -
    scope:
      path: ""
      type: demos
    values:
      layout: demo

slim:
  pretty: true
  format: html5

